name: Setup
description: Common setup for all workflows
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: "21"

    - uses: gradle/actions/setup-gradle@v4
