name: PR Checks

on:
  pull_request:

jobs:
  pr_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup

      - name: Build
        run: ./gradlew :app:assembleDebug

      - name: Test
        run: ./gradlew test

      - name: Test
        run: ./gradlew lint

      - uses: actions/upload-artifact@v4
        with:
          name: lint-results.html
          path: app/build/reports/lint-results-debug.html
